### ISSUE TITLE
Question regarding rampage_idr.sh comments

### ISSUE THREAD

**Issue by rcwchan** [ENCODE-DCC/long-rna-seq-pipeline#5]
Hi,

From what I understand, `rampage_idr.sh` should be run with the bed files resulting from two separate `rampage_peaks` runs (eg two replicates).

However, lines 8 and 9 of `rampage_idr.sh` state:

```
 peaks_a_bed=$1  # Rampage dumplicates marked bam file.
 peaks_b_bed=$2  # long-RNA-seq control bam file.
```
but `peaks_a_bed` should actually be (for example) `rampage_peaks_1.bed `and `peaks_b_bed` should be `rampage_peaks_2.bed`, correct? Not bamfiles and not rampage/control.

This may be an obvious question but I would like to be sure so that I run the pipeline correctly.
Thanks!

**Comment by ottojolanki** [comment]
The documentation https://github.com/ENCODE-DCC/long-rna-seq-pipeline/tree/master/dnanexus/rampage considering the rampage_idr applet, and also the flowchart seems to confirm your understanding to be correct. Thank you for pointing out the error in the comments considering the inputs of the script, I will fix that. If you have any other questions, I am happy to help!
